#%RAML 1.0 NamedExample
values:
  "Region": "Asia"
  "Currency": "INR"
  "Ex-Rate": 72.6353
  "minTemp":
    - #item 1
        Temp[0]: 301.26
        Temp[1]: 299.25
        Temp[2]: 304.22
        Temp[3]: 308.67
        Temp[4]: 310.5
  "maxTemp": 
    - #item 1
        Temp[0]: 302.06
        Temp[1]: 300.02
        Temp[2]: 304.31
        Temp[3]: 308.72
        Temp[4]: 310.5