#%RAML 1.0 NamedExample
value:
  "Country": "India"
  "Code": "IN"
  "Lat": 20
  "Lon": 77
  "Population": 1173108018
  "Deaths": 161582
  "Confirmed": 11969945
  "Recovered": 11321309
  "Critical": 487054
 