#%RAML 1.0 NamedExample
values:
  -
    "country": "India"
    "Code": "IN"
    "Lat": 20,
    "Lon": 77,
    "Population": 1173108018,
    "Deaths": 161582,
    "Confirmed": 11969945,
    "Recovered": 11321309,
    "Critical": 487054
  -
    "region": "Asia"
    "currencyName": "INR"
    "currencyEx-Rate": 72.6353
    "minTemp": [
        301.26,
        299.25,
        304.22,
        308.67,
        310.5
    ]
    "maxTemp": [
        302.06,
        300.02,
        304.31,
        308.72,
        310.5
    ]
  