#%RAML 1.0 DataType

type: object
properties:
  Country: string
  Code: string
  Lat: number
  Lon: number
  Population: number
  Deaths: number
  Confirmed: number
  Recovered: number
  Critical: number
examples: !include ..//Examples/Covid-19.raml