#%RAML 1.0 Library

traits:
  ErrorResponce: !include Traits/trait.raml
resourceTypes:
  Collection: !include Resources/resourceType.raml
types:
  DataType: !include DataTypes/dataType.raml
  ErrorMsgDataType: !include /DataTypes/errorMsgDataType.raml